# Generated by Django 4.2 on 2024-07-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqrcode',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
